### ISSUE TITLE
网页授权需要填写token做url接口验证吗？

### ISSUE THREAD

**Issue by phoenixg** [huanghua581/laravel-wechat-sdk#15]
还是只需appid和appsecret即可？

**Comment by phoenixg** [comment]
还有， 网页授权里，``getAccessTokenByCode`` 的参数``$code``是怎么来的呢？

**Comment by huanghua581** [comment]
appid 、 appsecret

token 是算出来的啊。看微信官网手册。

**Comment by phoenixg** [comment]
我说的不是access_token呀，是这里：
app/config/packages/cooper/wechat 中的配置文件 wechat.php 的token

**Comment by huanghua581** [comment]
这个 token 是微信验证服务器的填的，对应就行了啊。

**Comment by phoenixg** [comment]
但网页授权为什么需要这个token，还有，还需要url吧， 用哪个url？

**Comment by zieglar** [comment]
@phenixg 请去仔细阅读微信的相关文档

**Comment by phoenixg** [comment]
我认为网页授权是不依赖于填写服务器的token的

**Comment by zieglar** [comment]
http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html
网页授权需要的是 appid appsecert，如果你只是用网页授权，根本就无须用到这个扩展

**Comment by phoenixg** [comment]
@zieglar 当然不是必须的，但用不用到扩展的理由相信你在学习编程的时候就学过了，真是奇怪，明明知道我的意思，非要那么回答，气死我了！
