### ISSUE TITLE
这个类库似乎还没有微信模板发送功能？

### ISSUE THREAD

**Issue by hubs** [huanghua581/laravel-wechat-sdk#17]
似乎这个库没有微信模板发送？

**Comment by huanghua581** [comment]
暂时没有

**Comment by hubs** [comment]
/**
     * @param $to           关注者openId
     * @param $jumpUrl      点击跳转地址
     * @param $template_id  模板ID
     * @param array $data   模板数据
     * @return bool|string
     */
    public function sendTemplate($to,$jumpUrl,$template_id,$data=array()){
        $json = json_encode(
            array(
                'touser'        => $to,
                'template_id'   => $template_id,
                "url"           => $jumpUrl,
                "topcolor"      => Config::get('wechat::wechat.topcolor'),
                'data'          => $data,
            )
        );
        //如果是debug状态下,直接返回内容
        if(Input::get('debug') == 'true') return $json;

        $access_token = $this->getAccessToken();
        $url          = self::$_URL_API_ROOT . "/cgi-bin/message/template/send?access_token=$access_token";
        $res = self::post($url, $json);
        return self::checkIsSuc($res);
    }



--------------------------------------------------demo-----------------------------------------
 $openId="xxxxxxx";
        $templateArr=array(
            "first"=>array('value'=>'我们已收到您的货款，开始为您打包商品，请耐心等待: )','color'=>'#743A3A'),
            "orderMoneySum"=>array('value'=>'￥200元', 'color'=>'#173177'  ),
            "orderProductName"=>array('value'=>'iphone5s原装耳塞', 'color'=>'#173177'),
            "Remark"=>array('value'=>'如有问题请致电400-828-1878或直接在微信留言，JD将第一时间为您服务！')
        );
        $url="http://www.jd.com";
      \WeChatClient::sendTemplate($openId,$jumpUrl,$templateId,$templateParams);

**Comment by hubs** [comment]
我这边已测试通过了

**Comment by huanghua581** [comment]
提交代码吧

**Comment by hubs** [comment]
...好吧，我竟然不懂怎么提交代码...哎..等会学习下先...

**Comment by hubs** [comment]
remote: Permission to huanghua581/laravel-wechat-sdk.git denied to hubs.

好像没有权限.

**Comment by huanghua581** [comment]
先 fork  ，再提交。。
